### ISSUE TITLE
Nil map is emitted as empty map

### ISSUE THREAD

**Issue by atombender** [sanity-io/litter#2]
E.g.

```
var v map[string]interface{}
litter.Dump(v)
```

Prints:

```
map[string]interface {}
```

Possible same bug applies to slices?

**Comment by hasit** [comment]
In the case of making a literal

```
v := make(map[string]interface{})
litter.Dump(v)
```

Should print:
```
map[string]interface {}
```

Should a `isNil()` check be done before printing a nil map as @atombender mentioned?

**Comment by yinfredyue** [comment]
The problem still exists.
