### ISSUE TITLE
Output does not have correct float64 type for numbers.

### ISSUE THREAD

**Issue by jofowler** [sanity-io/litter#44]
I am using litter to output structures that include map[string]interface{} objects that were produced by the standard JSON encode/decode package. The standard JSON decoder returns all numbers in a property map as float64 values. When I run litter on the resulting struct it outputs structures where the numbers have no specified type, just literal values. As a result, numbers that had integral values get converter to int by the compiler. Is there a way to get litter to retain the float64 type specification?

**Comment by atombender** [comment]
Thanks, good point! Please take a look at whether the fix works for you?
