### ISSUE TITLE
"Latest" release is not the latest

### ISSUE THREAD

**Issue by AlekSi** [sanity-io/litter#45]
![image](https://user-images.githubusercontent.com/11512/148366771-f02763b5-2200-4409-a67a-a2db6c42259a.png)

https://github.com/sanity-io/litter/releases
https://github.com/sanity-io/litter/tags

It might be easier to just delete those two releases and keep only tags.

**Comment by atombender** [comment]
Thanks. I agree, as long as Go can rely on tags, we don't need releases.

**Comment by davidwbt** [comment]
@atombender it looks like you also removed the 1.2.0 tag, can this be restored?

**Comment by atombender** [comment]
I didn't — maybe that is something GitHub does automatically? I'll make sure it's put back.

**Comment by AlekSi** [comment]
Yes, I think deleting "release" also deletes the git tag.
Anyway, those tags are back! 🎉

**Comment by atombender** [comment]
TIL, thanks! I also did a new tag for the latest change.

**Comment by davidwbt** [comment]
Thanks we worked around this for now with a replace in our top level go.mod forcing a later version but should save some others some grief!

**Comment by atombender** [comment]
Sorry about that!
